import graphviz

def generate_rubric_graph():
    graph = graphviz.Digraph(format='svg')
    
    # Define nodes and edges for the graph
    graph.node('A', 'Project Setup and Structure')
    graph.node('B', 'Documentation')
    graph.node('C', 'Server-Side Implementation')
    graph.node('D', 'Client-Side Implementation')
    graph.node('E', 'Testing and Submission')

    graph.edge('A', 'B')
    graph.edge('B', 'C')
    graph.edge('C', 'D')
    graph.edge('D', 'E')

    # Generate and save the graph as an SVG file
    graph.render('rubric_graph')

if __name__ == '__main__':
    generate_rubric_graph()
