name: Graph Generation

on:
  push:
    branches:
      - main  # You can set this to your default branch name, like 'main' or 'master'

jobs:
  generate-graph:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Or another Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install graphviz

      - name: Generate Graph
        run: |
          python generate_graph.py  # This runs your script to generate the SVG graph

      - name: Commit the generated graph
        run: |
          git add rubric_graph.svg
          git commit -m "Add generated graph"
          git push
