name: Generate Rubric Graph

on:
  push:
    branches:
      - mincfranc-patch-1  # Trigger on push to this branch

jobs:
  generate-graph:
    runs-on: ubuntu-latest  # Using an Ubuntu machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Python version to use

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install Python dependencies

      - name: Install Graphviz
        run: |
          echo "Updating package list..."
          sudo apt-get update -y  # Update package list
          echo "Installing Graphviz..."
          sudo apt-get install -y graphviz  # Install Graphviz
          echo "Checking if Graphviz is installed..."
          dot -V  # This should print the version of Graphviz

      - name: Check Graphviz installation
        run: |
          echo "Running `which dot` to check for path..."
          which dot  # This checks if the `dot` command is available
          echo "Verifying Graphviz functionality..."
          dot -V  # This should print the version if Graphviz is installed correctly

      - name: Check system paths
        run: |
          echo "Checking system PATH..."
          echo $PATH  # This will print the system PATH to check if dot is in the PATH

      - name: Run Python script
        run: |
          echo "Running the Python script..."
          python Infrastructure/generate_graph.py  # Run the Python script
