name: Generate Rubric Graph

on:
  push:
    branches:
      - mincfranc-patch-1  # Trigger on push to this branch

jobs:
  generate-graph:
    runs-on: ubuntu-latest  # Using an Ubuntu machine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Python version to use

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install Python dependencies

      - name: Install Graphviz and check
        run: |
          echo "Updating packages..."
          sudo apt-get update -y  # Update package list
          echo "Installing Graphviz..."
          sudo apt-get install -y graphviz  # Install Graphviz
          echo "Graphviz version:"
          dot -V  # Print the version of Graphviz to check if 
